export type ErrorCode =
  | 'MEMBER_NOT_FOUND'
  | 'TODO_NOT_FOUND'
  | 'SAVE_TODO_NOT_FOUND_FROM_TARGET_PARENT'
  | 'TOKEN_EXPIRED'
  | 'INVALID_MEMBER_STATUS'
  | 'TODO_LIMIT_EXCEEDED'
  | 'METHOD_ARGUMENT_TYPE_MISMATCH'
  | 'PATH_ID_NOT_PROVIDED'
  | 'CATEGORY_NOT_FOUND'
  | 'SCHEDULE_NOT_FOUND'
  | 'PATH_NOT_FOUND'
  | 'INVALID_MEMBER_STATUS'
  | 'TODO_LIMIT_EXCEEDED'
  | 'ALREADY_ADDED_TODO'
  | 'METHOD_ARGUMENT_TYPE_MISMATCH'
  | 'PATH_ID_NOT_PROVIDED'
  | 'TODO_TYPE_MISMATCH'
  | 'MEMBER_CATEGORY_NOT_FOUND'
  | 'MEMBER_SAVED_ADDRESS_NOT_FOUND'
  | 'UNAUTHORIZED_PLAN_DELETION'
  | 'NOT_FOUND_PLAN'
  | 'INVALID_MOOD'
  | 'TOKEN_INVALID'
  | 'TOKEN_BLACKLISTED'
  | 'MISSING_TOKEN_IN_COOKIE'
  | 'REFRESH_TOKEN_EXPIRED'
  | 'NAVER_SERVICE_UNAVAILABLE';

export interface ResponseError {
  errorCode: ErrorCode;
  message: string;
}
