server:
  port: 8080
  servlet:
    contextPath: /api/v1

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 100
      password: ${REDIS_PASSWORD}
      connect-timeout: 100

  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
    ttl:
      app-push: ${APP_PUSH_DELAY_MS}
      member-status: ${MEMBER_STATUS_DELAY_MS}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

oauth2:
  client:
    registration:
      kakao:
        client_id: ${KAKAO_CLIENT_ID} # REST API
        redirect_uri: ${KAKAO_REDIRECT_URI}
        client_secret: ${KAKAO_CLIENT_SECRET} # Client Secret
        scope: account_email

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time-in-hours: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-expire-time-in-hours: ${JWT_REFRESH_TOKEN_TIME}

naver:
  client:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

kakao:
  client:
    authorization-key: ${KAKAO_AUTHORIZATION_KEY}

odsay:
  client:
    api-key: ${ODSAY_CLIENT_API_KEY}

vapid:
  public-key: ${VAPID_PUBLIC_KEY}
  private-key: ${VAPID_PRIVATE_KEY}

admin:
  email: ${ADMIN_EMAIL}

notification:
  url: ${NOTIFICATION_URL}

firebase:
  service-account-json: ${FIREBASE_SERVICE_ACCOUNT_JSON}

api:
  base-url: ${PROD_SERVER_URL}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: false
